### ISSUE TITLE
download and reindex stall on block 47654

### ISSUE THREAD

**Issue by anastrophe** [Internet-of-People/iop-core#3] opened 2017-10-06 22:18 UTC
### Describe the issue
Fresh download of blockchain stalls with errors
### Can you reliably reproduce the issue?
Yes, in that I forced a re-index it still stalls, though on a slightly different block
#### If so, please list the steps to reproduce below:
1. Install 6.0.0.57b2
2. run it, let it download blocks
3. stalls on block 47654

### Expected behaviour
full download of blockchain
### Actual behaviour
stops prematurely

### What version of iop-core are you using?
v6.0.0.57-486b7da

### Machine specs:
- OS: Win 10 pro
- CPU: i7-7700k
- RAM: 32GB
- Disk size: 500GB
- Disk Type (HD/SDD): m.2 ssd

### Any extra information that might be useful in the debugging process.
Here's the tail end of the debug log:
2017-10-06 22:08:55 UpdateTip: new best=000000000da66286066b07d9f269587271a71e179324c6bcf6a6527ee09a4328 height=47650 version=0x20000000 log2_work=51.747141 tx=51899 date='2017-08-09 06:49:38' progress=0.506066 cache=11.8MiB(86862txo)
2017-10-06 22:08:55 MinerDatabase: Adding Block 47651 to the database. Mined by pGhBhS7uFgbSneQtpUJeuWgBcGsZMseAZH
2017-10-06 22:08:55 MinerDatabase: Making entry for new block.
2017-10-06 22:08:55 Looking for admin actions.
2017-10-06 22:08:55 UpdateTip: new best=0000000011cd80078294b3056b15c9189bc8cff583a91b02521367aee0342952 height=47651 version=0x20000000 log2_work=51.747164 tx=51900 date='2017-08-09 06:50:03' progress=0.506076 cache=11.8MiB(86863txo)
2017-10-06 22:08:55 MinerDatabase: Adding Block 47652 to the database. Mined by p9LcK6gBCZYwgE7WtQVoSCP56k4frdjFQM
2017-10-06 22:08:55 MinerDatabase: Making entry for new block.
2017-10-06 22:08:55 Looking for admin actions.
2017-10-06 22:08:55 UpdateTip: new best=000000000329f984401a15d3b4762f2e8c1c4f6f4824db284820cda41d722c84 height=47652 version=0x20000000 log2_work=51.747187 tx=51901 date='2017-08-09 06:54:22' progress=0.506086 cache=11.8MiB(86864txo)
2017-10-06 22:08:55 MinerDatabase: Adding Block 47653 to the database. Mined by pUAw1VBDJuxBnWsgKYeWUdi8eEkho7AqF4
2017-10-06 22:08:55 MinerDatabase: Making entry for new block.
2017-10-06 22:08:55 Looking for admin actions.
2017-10-06 22:08:55 UpdateTip: new best=0000000003f49482ed3b4ebf2bc24c66785bd5399ec59b1eccee13dd0bc924f4 height=47653 version=0x20000000 log2_work=51.74721 tx=51902 date='2017-08-09 07:01:12' progress=0.506096 cache=11.8MiB(86865txo)
2017-10-06 22:08:55 MinerDatabase: Adding Block 47654 to the database. Mined by p9cHvGsRi5ZegmHSktujfMCcwynrckngJ9
2017-10-06 22:08:55 MinerDatabase: Making entry for new block.
2017-10-06 22:08:55 Looking for admin actions.
2017-10-06 22:08:55 UpdateTip: new best=00000000118494c6822e81f33ef08f074991a76fbae32425482a6bfecc26ec0a height=47654 version=0x20000000 log2_work=51.747233 tx=51903 date='2017-08-09 07:11:00' progress=0.506105 cache=11.8MiB(86866txo)
2017-10-06 22:08:55 Whitelist activated: Checking for Miner Signature.
2017-10-06 22:08:55 MinerCap: Has pCeTxNpqUchCKzGH5kJpcQozFQtvjguLgh exceeded miner cap? 140 > 55 ?
2017-10-06 22:08:55 MinerCap: pCeTxNpqUchCKzGH5kJpcQozFQtvjguLgh has exceeded cap. Not accepting Block.
2017-10-06 22:08:55 Invalid coinbase transaction: Miner pCeTxNpqUchCKzGH5kJpcQozFQtvjguLgh has exceeded the cap for this period.
2017-10-06 22:08:55 InvalidChainFound: invalid block=0000000000244692498052d6e6fc5c48937f8d7fa56b36901c9ec75766463c0f  height=47655  log2_work=51.747256  date=2017-08-09 07:18:19
2017-10-06 22:08:55 InvalidChainFound:  current best=00000000118494c6822e81f33ef08f074991a76fbae32425482a6bfecc26ec0a  height=47654  log2_work=51.747233  date=2017-08-09 07:11:00
2017-10-06 22:08:55 ERROR: ConnectTip(): ConnectBlock 0000000000244692498052d6e6fc5c48937f8d7fa56b36901c9ec75766463c0f failed
2017-10-06 22:08:55 InvalidChainFound: invalid block=0000000000244692498052d6e6fc5c48937f8d7fa56b36901c9ec75766463c0f  height=47655  log2_work=51.747256  date=2017-08-09 07:18:19
2017-10-06 22:08:55 InvalidChainFound:  current best=00000000118494c6822e81f33ef08f074991a76fbae32425482a6bfecc26ec0a  height=47654  log2_work=51.747233  date=2017-08-09 07:11:00
2017-10-06 22:08:55 Imported mempool transactions from disk: 0 successes, 0 failed, 0 expired
2017-10-06 22:08:56 ERROR: AcceptBlockHeader: block 0000000000b4c41cc12b6104048e4b4921b50dc1cb6cbef1dfea72b72827b443 is marked invalid
2017-10-06 22:08:56 ERROR: invalid header received
2017-10-06 22:08:56 ProcessMessages(headers, 162003 bytes) FAILED peer=0

I took a screenshot where it stalled on the initial download, and one now where it's stalled on the re-index. The 'current number of blocks' is different, even though the log reporst block 47654 as the best block in both the initial download and reindex.

<img width="456" alt="initial blockchain download stall" src="https://user-images.githubusercontent.com/1012545/31300625-8d1a21d6-aaa9-11e7-86a3-bf432bd6d243.png">
<img width="460" alt="re-index stall" src="https://user-images.githubusercontent.com/1012545/31300632-92cbb680-aaa9-11e7-8d2c-b13e7aa0ca24.png">

**Comment by Anfauglith** [comment] 2017-10-06 22:33
Thanks for the detailed bug report. The issue is strange, as I resynced myself on different machines several times, always without issues. Could you please enter "dumpminerstats" into the console while being stuck at the block you mentioned?

**Comment by anastrophe** [comment] 2017-10-06 22:35
sure - i tried just cut and pasting, but it came through blank, so here's a screenshot:
<img width="453" alt="2017-10-06 15_35_26-debug window" src="https://user-images.githubusercontent.com/1012545/31301035-09e47db8-aaac-11e7-8041-943e869ee5bc.png">

**Comment by Anfauglith** [comment] 2017-10-06 22:45
Ok so the database counts miners correctly, but somehow it is convinced that pCeTx... has mined 140 blocks, while on my machine it is convinced that he only mined 25.

I need to investigate that further. Thanks for your help!

**Comment by Anfauglith** [comment] 2017-10-06 22:47
Could you please just try with a completely empty folder?

**Comment by anastrophe** [comment] 2017-10-06 23:02
I'm willing to do so again - but note that that's how I started this time as well. Should I change - when the installer asks - the name of the directory to IoP-HD? Is it possible that has something to do with it? I'd be surprised if it did, but man is this odd!

**Comment by Anfauglith** [comment] 2017-10-06 23:03
Ok no, if you already tried that, then there is no point in doing so again. I just ran the release on my machine again. Syncs perfectly. I need to investigate... Thanks again, and sorry for the mess.

**Comment by anastrophe** [comment] 2017-10-06 23:04
No worries - I'm still going to do it, it's not much trouble. :)

**Comment by anastrophe** [comment] 2017-10-06 23:08
same error :(

2017-10-06 23:07:27 MinerDatabase: Adding Block 47647 to the database. Mined by pSwhaYL3wmjNKFv49khNgyUYQZNsXvgekK
2017-10-06 23:07:27 MinerDatabase: Making entry for new block.
2017-10-06 23:07:27 Looking for admin actions.
2017-10-06 23:07:27 UpdateTip: new best=000000000cb7caf1716199392a989c8a64a37aa939dac170d8e965fb4422a6a3 height=47647 version=0x20000000 log2_work=51.747072 tx=51896 date='2017-08-09 06:33:49' progress=0.505864 cache=11.8MiB(86859txo)
2017-10-06 23:07:27 MinerDatabase: Adding Block 47648 to the database. Mined by pGMEikN9LsdKWSG8V86KGtBvkKFnrAiiyz
2017-10-06 23:07:27 MinerDatabase: Making entry for new block.
2017-10-06 23:07:27 Looking for admin actions.
2017-10-06 23:07:27 UpdateTip: new best=0000000000d47c25d824849a5b18f5b978ff40e12548eb7fed0c76579e7f66b8 height=47648 version=0x20000000 log2_work=51.747095 tx=51897 date='2017-08-09 06:40:09' progress=0.505874 cache=11.8MiB(86860txo)
2017-10-06 23:07:27 MinerDatabase: Adding Block 47649 to the database. Mined by pH9MhzsLwQE9hoXFurdKjjP2yvZfaVedfu
2017-10-06 23:07:27 MinerDatabase: Making entry for new block.
2017-10-06 23:07:27 Looking for admin actions.
2017-10-06 23:07:27 UpdateTip: new best=00000000021a6f5b336d063f463662ec3181acaff271ea76b46aad96f90d9c71 height=47649 version=0x20000000 log2_work=51.747118 tx=51898 date='2017-08-09 06:44:53' progress=0.505883 cache=11.8MiB(86861txo)
2017-10-06 23:07:27 MinerDatabase: Adding Block 47650 to the database. Mined by p9RYej2GViCdoBqstaXhJwMTDbE8WR3zjU
2017-10-06 23:07:27 MinerDatabase: Making entry for new block.
2017-10-06 23:07:27 Looking for admin actions.
2017-10-06 23:07:27 UpdateTip: new best=000000000da66286066b07d9f269587271a71e179324c6bcf6a6527ee09a4328 height=47650 version=0x20000000 log2_work=51.747141 tx=51899 date='2017-08-09 06:49:38' progress=0.505893 cache=11.8MiB(86862txo)
2017-10-06 23:07:27 MinerDatabase: Adding Block 47651 to the database. Mined by pGhBhS7uFgbSneQtpUJeuWgBcGsZMseAZH
2017-10-06 23:07:27 MinerDatabase: Making entry for new block.
2017-10-06 23:07:27 Looking for admin actions.
2017-10-06 23:07:27 UpdateTip: new best=0000000011cd80078294b3056b15c9189bc8cff583a91b02521367aee0342952 height=47651 version=0x20000000 log2_work=51.747164 tx=51900 date='2017-08-09 06:50:03' progress=0.505903 cache=11.8MiB(86863txo)
2017-10-06 23:07:27 MinerDatabase: Adding Block 47652 to the database. Mined by p9LcK6gBCZYwgE7WtQVoSCP56k4frdjFQM
2017-10-06 23:07:27 MinerDatabase: Making entry for new block.
2017-10-06 23:07:27 Looking for admin actions.
2017-10-06 23:07:27 UpdateTip: new best=000000000329f984401a15d3b4762f2e8c1c4f6f4824db284820cda41d722c84 height=47652 version=0x20000000 log2_work=51.747187 tx=51901 date='2017-08-09 06:54:22' progress=0.505913 cache=11.8MiB(86864txo)
2017-10-06 23:07:27 MinerDatabase: Adding Block 47653 to the database. Mined by pUAw1VBDJuxBnWsgKYeWUdi8eEkho7AqF4
2017-10-06 23:07:27 MinerDatabase: Making entry for new block.
2017-10-06 23:07:27 Looking for admin actions.
2017-10-06 23:07:27 UpdateTip: new best=0000000003f49482ed3b4ebf2bc24c66785bd5399ec59b1eccee13dd0bc924f4 height=47653 version=0x20000000 log2_work=51.74721 tx=51902 date='2017-08-09 07:01:12' progress=0.505922 cache=11.8MiB(86865txo)
2017-10-06 23:07:27 MinerDatabase: Adding Block 47654 to the database. Mined by p9cHvGsRi5ZegmHSktujfMCcwynrckngJ9
2017-10-06 23:07:27 MinerDatabase: Making entry for new block.
2017-10-06 23:07:27 Looking for admin actions.
2017-10-06 23:07:27 UpdateTip: new best=00000000118494c6822e81f33ef08f074991a76fbae32425482a6bfecc26ec0a height=47654 version=0x20000000 log2_work=51.747233 tx=51903 date='2017-08-09 07:11:00' progress=0.505932 cache=11.8MiB(86866txo)
2017-10-06 23:07:27 Whitelist activated: Checking for Miner Signature.
2017-10-06 23:07:27 MinerCap: Has pCeTxNpqUchCKzGH5kJpcQozFQtvjguLgh exceeded miner cap? 140 > 55 ?
2017-10-06 23:07:27 MinerCap: pCeTxNpqUchCKzGH5kJpcQozFQtvjguLgh has exceeded cap. Not accepting Block.
2017-10-06 23:07:27 Invalid coinbase transaction: Miner pCeTxNpqUchCKzGH5kJpcQozFQtvjguLgh has exceeded the cap for this period.
2017-10-06 23:07:27 Misbehaving: 104.155.51.239:4877 peer=3 (0 -> 100) BAN THRESHOLD EXCEEDED
2017-10-06 23:07:27 InvalidChainFound: invalid block=0000000000244692498052d6e6fc5c48937f8d7fa56b36901c9ec75766463c0f  height=47655  log2_work=51.747256  date=2017-08-09 07:18:19
2017-10-06 23:07:27 InvalidChainFound:  current best=00000000118494c6822e81f33ef08f074991a76fbae32425482a6bfecc26ec0a  height=47654  log2_work=51.747233  date=2017-08-09 07:11:00
2017-10-06 23:07:27 ERROR: ConnectTip(): ConnectBlock 0000000000244692498052d6e6fc5c48937f8d7fa56b36901c9ec75766463c0f failed
2017-10-06 23:07:27 InvalidChainFound: invalid block=0000000000244692498052d6e6fc5c48937f8d7fa56b36901c9ec75766463c0f  height=47655  log2_work=51.747256  date=2017-08-09 07:18:19
2017-10-06 23:07:27 InvalidChainFound:  current best=00000000118494c6822e81f33ef08f074991a76fbae32425482a6bfecc26ec0a  height=47654  log2_work=51.747233  date=2017-08-09 07:11:00

**Comment by Anfauglith** [comment] 2017-10-06 23:31
Ok wow... 
How could I not see that your dumpminerstats does not show ANY info on the individual miners?! 
Can you run `dumpminerstats pCeTxNpqUchCKzGH5kJpcQozFQtvjguLgh`, please?

**Comment by anastrophe** [comment] 2017-10-07 02:10
Hey there, I got an email requesting dumpminerstats on the address in question but for some reason i don't see that comment here. But regardless, here's that output:

<img width="460" alt="2017-10-06 19_09_53-debug window" src="https://user-images.githubusercontent.com/1012545/31303861-f87bdd3c-aac9-11e7-9cef-01c033d59fbc.png">

**Comment by Anfauglith** [comment] 2017-10-07 10:57
Hey, yeah, that was me, I found someone else who did it for me. Thanks anyway.

I think I know what the issue is. I use an iterator over the database both to reset the counter for miners at the beginning of a window and to print the miner stats. Somehow this iterator does not find a single address in your case, so the counters don't get reset at the beginning of a window and no miners are printed when using dumpminerstats. LevelDB should be lexically sorted by key, but possibly Win has a different lexical sorting system from UNIX?! Anyway, now that I see the problem, I will try to find a solution.

**Comment by anastrophe** [comment] 2017-10-08 00:02
Thank you very much for looking into it! If you need any additional info just let me know, I'm happy to help.

**Comment by anastrophe** [comment] 2017-10-08 02:12
By the way, is there any sort of workaround that I can do to get past this in the meantime?

**Comment by Anfauglith** [comment] 2017-10-08 10:08
I do not have a workaround, sorry, but I am testing a fix right now. You can help me if you want. Contact me in Discord or the Telegram Group

**Comment by Anfauglith** [comment] 2017-10-10 09:27
Ok, the fix seems to be working. New Beta will be released in the next few days.

**Comment by anastrophe** [comment] 2017-10-10 19:31
Thanks very much.

**Comment by Anfauglith** [comment] 2017-10-14 22:09
Fixed in the new beta

**Closed by Anfauglith** 2017-10-14 22:09 UTC
